image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - java -jar ./artifacts/app-ibank-build-for-testers.jar &

test_script:
  - chmod +x gradlew
  - ./gradlew test --info -Dselenide.headless=true